workflows:
  ios-build-and-upload:
    name: Build and Upload to App Store
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "Space Bubble Match - LouJJStudios"
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "Space Bubble Match - LouJJStudios"
    publishing:
      app_store_connect:
        auth: integration
